/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_hangman;

/**
 *
 * @author USER
 */
public class GamePlay extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GamePlay.class.getName());

    /**
     * Creates new form GamePlay
     */
    public GamePlay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/BACK.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/paii.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Hangman paii.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -130, 500, 330));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/A.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(this::GroupButtonActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/B.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(this::GroupButtonActionPerformed);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 210, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/C.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(this::GroupButtonActionPerformed);
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 210, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/D.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(this::GroupButtonActionPerformed);
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 210, -1, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/E.png"))); // NOI18N
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(this::GroupButtonActionPerformed);
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, -1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/F.png"))); // NOI18N
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(this::GroupButtonActionPerformed);
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 270, -1, -1));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/G.png"))); // NOI18N
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.addActionListener(this::GroupButtonActionPerformed);
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 270, -1, -1));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/H.png"))); // NOI18N
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.addActionListener(this::GroupButtonActionPerformed);
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 270, -1, -1));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/I.png"))); // NOI18N
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.addActionListener(this::GroupButtonActionPerformed);
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, -1, -1));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/J.png"))); // NOI18N
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.addActionListener(this::GroupButtonActionPerformed);
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 340, -1, -1));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/K.png"))); // NOI18N
        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.addActionListener(this::GroupButtonActionPerformed);
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 340, -1, -1));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/L.png"))); // NOI18N
        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.addActionListener(this::GroupButtonActionPerformed);
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 340, -1, -1));

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/M.png"))); // NOI18N
        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        jButton14.addActionListener(this::GroupButtonActionPerformed);
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 400, -1, -1));

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/N.png"))); // NOI18N
        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        jButton15.addActionListener(this::GroupButtonActionPerformed);
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 400, -1, -1));

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/O.png"))); // NOI18N
        jButton16.setBorderPainted(false);
        jButton16.setContentAreaFilled(false);
        jButton16.addActionListener(this::GroupButtonActionPerformed);
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, -1, -1));

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/P.png"))); // NOI18N
        jButton17.setBorderPainted(false);
        jButton17.setContentAreaFilled(false);
        jButton17.addActionListener(this::GroupButtonActionPerformed);
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 400, -1, -1));

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Q.png"))); // NOI18N
        jButton18.setBorderPainted(false);
        jButton18.setContentAreaFilled(false);
        jButton18.addActionListener(this::GroupButtonActionPerformed);
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 460, -1, -1));

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/R.png"))); // NOI18N
        jButton19.setBorderPainted(false);
        jButton19.setContentAreaFilled(false);
        jButton19.addActionListener(this::GroupButtonActionPerformed);
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 460, -1, -1));

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/S.png"))); // NOI18N
        jButton20.setBorderPainted(false);
        jButton20.setContentAreaFilled(false);
        jButton20.addActionListener(this::GroupButtonActionPerformed);
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 460, -1, -1));

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/T.png"))); // NOI18N
        jButton21.setBorderPainted(false);
        jButton21.setContentAreaFilled(false);
        jButton21.addActionListener(this::GroupButtonActionPerformed);
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 520, -1, -1));

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/U.png"))); // NOI18N
        jButton22.setBorderPainted(false);
        jButton22.setContentAreaFilled(false);
        jButton22.addActionListener(this::GroupButtonActionPerformed);
        getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 550, -1, -1));

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/V.png"))); // NOI18N
        jButton23.setBorderPainted(false);
        jButton23.setContentAreaFilled(false);
        jButton23.addActionListener(this::GroupButtonActionPerformed);
        getContentPane().add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 520, -1, -1));

        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/W.png"))); // NOI18N
        jButton24.setBorderPainted(false);
        jButton24.setContentAreaFilled(false);
        jButton24.addActionListener(this::GroupButtonActionPerformed);
        getContentPane().add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 520, -1, -1));

        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/X.png"))); // NOI18N
        jButton25.setBorderPainted(false);
        jButton25.setContentAreaFilled(false);
        jButton25.addActionListener(this::GroupButtonActionPerformed);
        getContentPane().add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 580, -1, -1));

        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Y.png"))); // NOI18N
        jButton26.setBorderPainted(false);
        jButton26.setContentAreaFilled(false);
        jButton26.addActionListener(this::GroupButtonActionPerformed);
        getContentPane().add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 580, -1, -1));

        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Z.png"))); // NOI18N
        jButton27.setBorderPainted(false);
        jButton27.setContentAreaFilled(false);
        jButton27.addActionListener(this::GroupButtonActionPerformed);
        getContentPane().add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 580, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Head.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Body.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, 90, 90));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Maikwankor.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Left Arm.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Right arm.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 520, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/right leg.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 550, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/left leg.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/BACKGROUND WANG.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Home next = new Home();
       next.setVisible(true);
       this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void GroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GroupButtonActionPerformed
        javax.swing.JButton clickedButton = (javax.swing.JButton) evt.getSource();
        clickedButton.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_GroupButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GamePlay().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
